# CI file to enable and use Github Actions
# Maintainer: Marius Stanca <me@marius.xyz>

name: Terraform Analysis

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: "Security Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.2"

      - name: Install Python version
        uses: gabrielfalcao/pyenv-action@v17
        with:
          default: "3.9.7"
          command: pip install -U pip

      - name: Install dependencies and create a virtual environment
        run: |
          pip install pipenv==2024.0.3
          pipenv install --deploy --dev

      - name: Static code analysis
        run: pipenv run checkov --directory infra
